### ISSUE TITLE
"All / Next" setting doesn't work

### ISSUE THREAD

**Issue by Manujito** [RemiRigal/Plex-Auto-Languages#12] opened 2022-04-25 14:27 UTC
The setting doesn't work for me. It always changes all the episodes in the entire season/show even if I put "next" in the config file.

**Comment by Manujito** [comment] 2022-04-25 16:24
I'm on version 1.25.9.5721 of Plex.
I'm running it natively with Python, version 3.10.1.

I tried your command for the PlexAPI version but it didn't work, it just returns: "Error while finding module specification for 'import plexapi; print(plexapi.__version__)' (ModuleNotFoundError: No module named 'import plexapi; print(plexapi')"
Sounds like a syntax error, not sure what to change.

**Comment by RemiRigal** [comment] 2022-04-25 19:44
My bad, the command is (`-c` instead of `-m`):
`python3 -c "import plexapi; print(plexapi.__version__)"`

I assume that you have spaces/tab before every parameter except `plexautolanguages` right ? The formatting is not great in GitHub.

**Comment by Manujito** [comment] 2022-04-30 13:08
Sorry for the long wait. PlexAPI version is 4.10.1.

I just updated Plex-Auto-Languages and the result is the same. When the update happens, even if I have "next" in my config file, the entire season gets changed.

**Comment by RemiRigal** [comment] 2022-04-30 13:42
The range of episodes is now logged for every language change. You should have something like the following:
```plaintext
2022-04-30 13:22:21,430 [INFO] Language update: Show: Attack on Titan | User: xxxx | Audio: Italian (AC3 5.1) | Subtitles: Italian (SRT) | Updated episodes: 21/21 (S01E05 - S01E25)
```
With `(S01E05 - S01E25)` indicating the episodes that have been checked for potential language update. Can you try watching something like S01E04 and see if PlexAutoLanguages still tries to update S01E01 ?

If the issue is still there, try to set the `update_strategy` parameter with the environment variable `UPDATE_STRATEGY`, you will have an explicit log on startup if this is picked up correctly.

**Comment by Manujito** [comment] 2022-04-30 13:46
Ok, nevermind. This is completely my fault for not understanding what that option meant.
I thought it meant that "next" would only change the next episode, singular, and that "all" would change all the remaining episodes.

I'm sorry for wasting your time, the option works as expected.

**Comment by RemiRigal** [comment] 2022-04-30 13:54
No worries, the parameter could have been described better !

Would you like an option to update only the next episode ?

**Comment by Manujito** [comment] 2022-04-30 13:58
It's absolutely not a priority and I'm not sure I would even use it, but thanks for your interest. I like to test things out as much as I can so I just thought the option was not working as intended.

Now that I know what it does, i'm actually using the "all" option myself.

**Comment by RemiRigal** [comment] 2022-04-30 14:08
I'm closing this issue then. Feel free to reopen it if you need this feature in the future.

Thank you for opening an issue !

**Closed by RemiRigal** 2022-04-30 14:08 UTC
Labels: bug
